import os, sys, json
from playwright.sync_api import sync_playwright
BASE = 'file://' + os.path.abspath(sys.argv[1]) + '/'
ok = []; falhas = []; problemas = []
def chk(nome, cond, extra=''):
    (ok if cond else falhas).append(nome); print(('OK   ' if cond else 'FALHA') + ' ' + nome + (('  -> ' + str(extra)) if extra != '' else ''))
def novo(b, w=1366, h=860):
    ctx = b.new_context(viewport={'width': w, 'height': h}); pg = ctx.new_page()
    pg.on('console', lambda m: m.type == 'error' and problemas.append(('console', m.text)))
    pg.on('pageerror', lambda e: problemas.append(('pageerror', str(e))))
    pg.on('dialog', lambda d: d.accept())
    return ctx, pg
def entrar(pg, u, s):
    pg.goto(BASE + 'login.html'); pg.fill('#login-usuario', u); pg.fill('#login-senha', s); pg.click('#form-login button[type=submit]')
def txt(pg, sel): return pg.locator(sel).first.inner_text().strip()

with sync_playwright() as p:
    b = p.chromium.launch(**({'executable_path': os.environ['CHROME']} if os.environ.get('CHROME') else {}))
    # ---------- 1. LOGIN ----------
    ctx, pg = novo(b)
    pg.goto(BASE + 'dashboard.html'); pg.wait_for_timeout(300)
    chk('rota protegida sem sessão redireciona ao login', 'login.html' in pg.url, pg.url.split('/')[-1])
    entrar(pg, 'admin', 'errada'); pg.wait_for_timeout(300)
    chk('login inválido -> mensagem genérica', 'Usuário ou senha inválidos' in pg.inner_text('#form-login'), pg.inner_text('#form-login')[-120:].replace('\n', ' | '))
    pg.fill('#login-usuario', ''); pg.fill('#login-senha', ''); pg.click('#form-login button[type=submit]'); pg.wait_for_timeout(200)
    chk('login vazio -> erro de campo', txt(pg, '#erro-login') != '', txt(pg, '#erro-login'))
    entrar(pg, 'admin', 'admin'); pg.wait_for_url('**/dashboard.html')
    chk('admin/admin -> dashboard', pg.url.endswith('dashboard.html'))
    chk('dono vê 9 itens no menu', pg.locator('#menu a').count() == 9, pg.locator('#menu a').count())
    canv = pg.evaluate("[...document.querySelectorAll('canvas')].map(c=>[c.width,c.height,c.getAttribute('aria-label')])")
    chk('gráficos canvas desenhados', len(canv) >= 1 and all(c[0] > 0 for c in canv), canv)

    # ---------- 2. CLIENTE: CPF INVÁLIDO ----------
    pg.goto(BASE + 'clientes.html'); pg.wait_for_timeout(300)
    n0 = pg.evaluate("Vibe.Dados.listar('clientes').length")
    pg.click('#btn-novo'); pg.wait_for_timeout(200)
    pg.fill('#cli-nome', 'Teste Cpf'); pg.fill('#cli-telefone', '51988887777'); pg.fill('#cli-cpf', '12345678900')
    chk('máscara de CPF aplicada', pg.input_value('#cli-cpf') == '123.456.789-00', pg.input_value('#cli-cpf'))
    pg.click('#form-cliente button[type=submit]'); pg.wait_for_timeout(200)
    chk('CPF com DV errado rejeitado', 'dígitos verificadores' in txt(pg, '#erro-cpf'), txt(pg, '#erro-cpf'))
    chk('campo CPF com aria-invalid', pg.get_attribute('#cli-cpf', 'aria-invalid') == 'true')
    pg.fill('#cli-cpf', '1234567890'); pg.click('#form-cliente button[type=submit]'); pg.wait_for_timeout(200)
    chk('CPF com 10 dígitos rejeitado', '11 dígitos' in txt(pg, '#erro-cpf'), txt(pg, '#erro-cpf'))
    pg.fill('#cli-cpf', '111.111.111-11'); pg.click('#form-cliente button[type=submit]'); pg.wait_for_timeout(200)
    chk('CPF repetido 111... rejeitado', txt(pg, '#erro-cpf') != '', txt(pg, '#erro-cpf'))
    pg.fill('#cli-cpf', '529.982.247-25'); pg.fill('#cli-telefone', '5199'); pg.click('#form-cliente button[type=submit]'); pg.wait_for_timeout(200)
    chk('telefone curto rejeitado', txt(pg, '#erro-telefone') != '', txt(pg, '#erro-telefone'))
    pg.fill('#cli-telefone', '(51) 98888-7777'); pg.fill('#cli-email', 'a@'); pg.click('#form-cliente button[type=submit]'); pg.wait_for_timeout(200)
    chk('email inválido rejeitado', txt(pg, '#erro-email') != '', txt(pg, '#erro-email'))
    pg.fill('#cli-email', 'teste@vibe.com'); pg.click('#form-cliente button[type=submit]'); pg.wait_for_timeout(300)
    n1 = pg.evaluate("Vibe.Dados.listar('clientes').length")
    chk('CPF válido 529.982.247-25 salva cliente', n1 == n0 + 1, (n0, n1))
    pg.reload(); pg.wait_for_timeout(300)
    chk('cliente persiste após reload (localStorage)', 'Teste Cpf' in pg.inner_text('#tabela-clientes'))

    # ---------- 3. AGENDA: CONFLITO E DATA ----------
    pg.goto(BASE + 'agenda.html'); pg.wait_for_timeout(300)
    info = pg.evaluate("""(() => { const h = Vibe.UI.hojeIso(); const a = Vibe.Dados.listar('agendamentos').find(x => x.dataHora.startsWith(h) && x.status==='AGENDADO' && x.dataHora.slice(11,16)==='14:00'); return a; })()""")
    chk('seed tem agendamento hoje 14:00', info is not None, info)
    pg.click('#btn-novo'); pg.wait_for_timeout(200)
    pg.select_option('#ag-cliente', str(9)); pg.select_option('#ag-barbeiro', str(info['idBarbeiro']))
    hoje_br = pg.evaluate("Vibe.Regras.formatarData(Vibe.UI.hojeIso())")
    pg.fill('#ag-data', hoje_br.replace('/', '')); pg.fill('#ag-hora', '1415')
    chk('máscara data/hora', pg.input_value('#ag-data') == hoje_br and pg.input_value('#ag-hora') == '14:15', (pg.input_value('#ag-data'), pg.input_value('#ag-hora')))
    pg.click('#form-agendamento button[type=submit]'); pg.wait_for_timeout(300)
    chk('conflito de 30 min detectado', 'já tem atendimento próximo' in txt(pg, '#erro-hora'), txt(pg, '#erro-hora'))
    sug = pg.locator('#sugestoes button').count()
    chk('sugestões de horários livres exibidas', sug > 0, sug)
    pg.fill('#ag-data', '31/02/2026'); pg.fill('#ag-hora', '10:00'); pg.click('#form-agendamento button[type=submit]'); pg.wait_for_timeout(200)
    chk('31/02/2026 rejeitada', txt(pg, '#erro-data') != '', txt(pg, '#erro-data'))
    pg.fill('#ag-data', hoje_br); pg.fill('#ag-hora', '25:00'); pg.click('#form-agendamento button[type=submit]'); pg.wait_for_timeout(200)
    chk('hora 25:00 rejeitada', txt(pg, '#erro-hora') != '', txt(pg, '#erro-hora'))
    amanha = pg.evaluate("(()=>{const d=new Date();do{d.setDate(d.getDate()+1)}while(d.getDay()===0);return Vibe.Regras.formatarData(Vibe.Regras.isoData(d))})()")
    livre = pg.evaluate(f"(()=>{{const iso=Vibe.Regras.data('{amanha}');return Vibe.Servicos.Agenda.horariosDisponiveis(iso,{info['idBarbeiro']}).find(s=>s.disponivel).hora}})()")
    pg.fill('#ag-data', amanha); pg.fill('#ag-hora', livre)
    na0 = pg.evaluate("Vibe.Dados.listar('agendamentos').length")
    pg.click('#form-agendamento button[type=submit]'); pg.wait_for_timeout(300)
    na1 = pg.evaluate("Vibe.Dados.listar('agendamentos').length")
    chk(f'agendamento sem conflito salvo ({amanha} {livre})', na1 == na0 + 1, (na0, na1))
    chk('linha do tempo renderizada', pg.locator('#linha-tempo .lt-celula, #linha-tempo [class^=lt-]').count() > 0, pg.locator('#linha-tempo *').count())

    # ---------- 4. ATENDIMENTO COM RESGATE ----------
    alvo = pg.evaluate("""(() => { const pend = Vibe.Dados.listar('agendamentos').filter(a=>a.status==='AGENDADO' && a.dataHora.startsWith(Vibe.UI.hojeIso()));
        const c = pend.map(a=>[a, Vibe.Dados.obter('clientes', a.idCliente)]).find(([a,c])=>c.pontos>=100); return c ? {ag:c[0], cli:c[1]} : {pend: pend.map(a=>[a.id, Vibe.Dados.obter('clientes',a.idCliente).pontos])}; })()""")
    if 'ag' not in alvo:
        print('   nenhum pendente de hoje com >=100 pts; ajustando pontos do cliente do 1º pendente para o teste', alvo)
        pid = alvo['pend'][0][0]
        alvo = pg.evaluate(f"(()=>{{const a=Vibe.Dados.obter('agendamentos',{pid});const c=Vibe.Dados.obter('clientes',a.idCliente);Vibe.Dados.atualizar('clientes',c.id,{{pontos:230}});return {{ag:a,cli:Vibe.Dados.obter('clientes',c.id)}}}})()")
    ag, cli = alvo['ag'], alvo['cli']
    barb = pg.evaluate(f"Vibe.Dados.obter('barbeiros',{ag['idBarbeiro']})")
    print(f"   alvo: agendamento {ag['id']} {ag['dataHora']} cliente {cli['nome']} {cli['pontos']} pts, barbeiro {barb['nome']} {barb['comissao']}%")
    pg.goto(BASE + f"atendimento.html?agendamento={ag['id']}"); pg.wait_for_timeout(400)
    chk('pré-seleção via ?agendamento=', pg.input_value('#at-agendamento') == str(ag['id']), pg.input_value('#at-agendamento'))
    pg.click('#form-atendimento button[type=submit]'); pg.wait_for_timeout(200)
    chk('sem itens -> erro', txt(pg, '#erro-itens') != '', txt(pg, '#erro-itens'))
    # Corte + Barba (70) + Platinado (120) = 190
    ids = pg.evaluate("Vibe.Dados.listar('servicos').filter(s=>['Corte + Barba','Platinado / Descoloração'].includes(s.nome)).map(s=>s.id)")
    for i in ids: pg.check(f'#lista-itens input[value="{i}"]')
    pg.wait_for_timeout(200)
    chk('subtotal ao vivo R$ 190,00', '190,00' in txt(pg, '#rc-bruto'), txt(pg, '#rc-bruto'))
    chk('checkbox de resgate habilitado', pg.is_enabled('#at-resgatar'), txt(pg, '#resgate-ajuda'))
    pg.check('#at-resgatar'); pg.wait_for_timeout(200)
    esperado = pg.evaluate(f"Vibe.Regras.calcularAtendimento({{itens:[{{preco:190}}], percentComissao:{barb['comissao']}, pontosCliente:{cli['pontos']}, resgatar:true}})")
    print('   esperado (Regras):', esperado)
    blocos = min(cli['pontos'] // 100, int(190 * 0.5 // 10)); desc = blocos * 10; pago = 190 - desc
    chk(f'desconto = {blocos} blocos = R$ {desc}', esperado['desconto'] == desc and esperado['pontosResgatados'] == blocos * 100, esperado)
    chk('recibo mostra desconto e total', f'{desc},00' in txt(pg, '#rc-desconto') and f'{pago},00' in txt(pg, '#rc-pago'), (txt(pg, '#rc-desconto'), txt(pg, '#rc-pago')))
    com = round(pago * barb['comissao']) / 100
    chk('comissão = round(pago*%)/100', abs(esperado['comissao'] - com) < 0.001, (esperado['comissao'], com, txt(pg, '#rc-comissao')))
    chk('pontos ganhos = floor(pago/10)', esperado['pontosGanhos'] == pago // 10, esperado['pontosGanhos'])
    pg.click('#form-atendimento button[type=submit]'); pg.wait_for_timeout(200)
    chk('sem pagamento -> erro', txt(pg, '#erro-pagamento') != '', txt(pg, '#erro-pagamento'))
    pg.click('label.chip:has(input[value="PIX"])'); pg.click('#form-atendimento button[type=submit]'); pg.wait_for_timeout(400)
    depois = pg.evaluate(f"({{ag: Vibe.Dados.obter('agendamentos',{ag['id']}), cli: Vibe.Dados.obter('clientes',{cli['id']}), mov: Vibe.Dados.listar('movimentos').slice(-1)[0]}})")
    chk('agendamento CONCLUIDO', depois['ag']['status'] == 'CONCLUIDO', depois['ag']['status'])
    chk('saldo de pontos do cliente atualizado', depois['cli']['pontos'] == cli['pontos'] - blocos * 100 + pago // 10, (cli['pontos'], depois['cli']['pontos']))
    chk('movimento de caixa gravado', abs(depois['mov']['valor'] - pago) < 0.001 and depois['mov']['formaPagamento'] == 'PIX', depois['mov'])
    chk('modal de conclusão aberto', pg.locator('#modal-concluido[open]').count() == 1)
    pg.screenshot(path='/tmp/s8/fluxo_concluido.png')
    # caixa / relatórios
    pg.goto(BASE + 'caixa.html'); pg.wait_for_timeout(300)
    chk('caixa lista movimentos', pg.locator('table tbody tr').count() > 0, pg.locator('table tbody tr').count())
    pg.goto(BASE + 'relatorios.html'); pg.wait_for_timeout(400)
    abas = pg.locator('#abas-relatorio .aba'); vistos = []
    for i in range(abas.count()):
        abas.nth(i).click(); pg.wait_for_timeout(250)
        vistos.append((abas.nth(i).inner_text(), pg.evaluate("(()=>{const c=document.querySelector('#painel-relatorio canvas');return c?c.width:0})()"), pg.locator('#painel-relatorio table tbody tr').count()))
    chk('relatórios: todas as abas com gráfico e tabela', all(v[1] > 0 and v[2] > 0 for v in vistos), vistos)
    # alterar senha
    pg.goto(BASE + 'alterar-senha.html'); pg.wait_for_timeout(200)
    pg.fill('#s-atual', 'admin'); pg.fill('#s-nova', 'admin'); pg.fill('#s-confirmacao', 'admin'); pg.click('#form-senha button[type=submit]'); pg.wait_for_timeout(200)
    chk('nova senha igual à atual rejeitada', txt(pg, '#erro-nova') != '', txt(pg, '#erro-nova'))
    pg.fill('#s-nova', 'nova123'); pg.fill('#s-confirmacao', 'nova12'); pg.click('#form-senha button[type=submit]'); pg.wait_for_timeout(200)
    chk('confirmação diferente rejeitada', txt(pg, '#erro-confirmacao') != '', txt(pg, '#erro-confirmacao'))
    # sair
    pg.click('#btn-sair'); pg.wait_for_timeout(200); pg.click('dialog[open] button[value=sim]'); pg.wait_for_timeout(400)
    chk('sair volta para login/início', 'login.html' in pg.url or 'index.html' in pg.url, pg.url.split('/')[-1])
    ctx.close()

    # ---------- 5. PERFIS ----------
    ctx, pg = novo(b)
    entrar(pg, '555.555.555-55', '123'); pg.wait_for_url('**/dashboard.html')
    menu_g = pg.eval_on_selector_all('#menu a', 'as => as.map(a => a.textContent.trim())')
    chk('gerente: menu sem Serviços', 'Serviços e produtos' not in menu_g and 'Clientes' in menu_g, menu_g)
    pg.goto(BASE + 'servicos.html'); pg.wait_for_timeout(400)
    chk('gerente bloqueado em servicos.html', 'dashboard.html' in pg.url, pg.url.split('/')[-1])
    ctx.close()
    ctx, pg = novo(b)
    entrar(pg, '11111111111', '123'); pg.wait_for_url('**/dashboard.html')
    menu_b = pg.eval_on_selector_all('#menu a', 'as => as.map(a => a.textContent.trim())')
    chk('barbeiro: menu restrito', 'Clientes' not in menu_b and 'Funcionários' not in menu_b and 'Atendimento' in menu_b, menu_b)
    pg.goto(BASE + 'agenda.html'); pg.wait_for_timeout(300)
    chk('barbeiro: agenda em modo consulta', pg.locator('#btn-novo').is_hidden() or pg.locator('#aviso-consulta').is_visible())
    opts = pg.eval_on_selector_all('#at-agendamento option', 'o=>o.length') if False else None
    pg.goto(BASE + 'atendimento.html'); pg.wait_for_timeout(300)
    meus = pg.evaluate("(()=>{const u=Vibe.Auth.usuario();return [...document.querySelectorAll('#at-agendamento option')].filter(o=>o.value).every(o=>Vibe.Dados.obter('agendamentos',+o.value).idBarbeiro===u.idBarbeiro)})()")
    chk('barbeiro só vê seus agendamentos no atendimento', meus)
    pg.goto(BASE + 'clientes.html'); pg.wait_for_timeout(300)
    chk('barbeiro bloqueado em clientes.html', 'dashboard.html' in pg.url)
    ctx.close()

    # ---------- 6. AGENDAR ONLINE ----------
    ctx, pg = novo(b)
    pg.goto(BASE + 'agendar.html'); pg.wait_for_timeout(300)
    pg.click('#btn-avancar'); pg.wait_for_timeout(150)
    chk('agendar: exige serviço', pg.locator('#erro-servicos, .erro-campo:visible').first.inner_text().strip() != '')
    pg.click('label:has(input[name="servicos"]) >> nth=2'); pg.click('#btn-avancar'); pg.wait_for_timeout(150)
    pg.click('label:has(input[name="barbeiro"]) >> nth=1'); pg.click('#btn-avancar'); pg.wait_for_timeout(200)
    dias = pg.locator('#op-dias .dia').count(); fechados = pg.locator('#op-dias .dia[disabled]').count()
    chk('14 dias exibidos, domingo fechado', dias == 14 and fechados >= 2, (dias, fechados))
    pg.click('#op-dias .dia:not([disabled]) >> nth=1'); pg.wait_for_timeout(150)
    slots = pg.locator('#op-horas .horario').count(); occ = pg.locator('#op-horas .horario[disabled]').count()
    chk('grade de horários gerada', slots == 20, (slots, occ))
    pg.click('#op-horas .horario:not([disabled]) >> nth=0'); pg.click('#btn-avancar'); pg.wait_for_timeout(150)
    pg.fill('#ag-nome', 'Cliente Online'); pg.fill('#ag-telefone', '51977776666')
    na0 = pg.evaluate("Vibe.Dados.listar('agendamentos').length")
    pg.click('#btn-confirmar'); pg.wait_for_timeout(400)
    na1 = pg.evaluate("Vibe.Dados.listar('agendamentos').length")
    novo_ag = pg.evaluate("Vibe.Dados.listar('agendamentos').slice(-1)[0]")
    chk('agendamento online criado (origem ONLINE)', na1 == na0 + 1 and novo_ag.get('origem') == 'ONLINE', novo_ag)
    chk('cliente criado pelo telefone', pg.evaluate("!!Vibe.Servicos.Clientes.porTelefone('51977776666')"))
    links = pg.eval_on_selector_all('a[download], a[href*="wa.me"]', 'as=>as.map(a=>a.getAttribute("download")||a.href.slice(0,30))')
    chk('confirmação com .ics e WhatsApp', len(links) >= 2, links)
    pg.screenshot(path='/tmp/s8/fluxo_agendar_ok.png')
    # fidelidade simulador
    pg.goto(BASE + 'fidelidade.html'); pg.wait_for_timeout(300)
    pg.screenshot(path='/tmp/s8/fidelidade.png', full_page=True)
    # recuperar senha
    pg.goto(BASE + 'recuperar-senha.html'); pg.fill('#rec-login', '555.555.555-55'); pg.click('#form-recuperar button[type=submit]'); pg.wait_for_timeout(300)
    chk('recuperar senha gera provisória', pg.inner_text('#rec-resultado').strip() != '', pg.inner_text('#rec-resultado')[:150].replace('\n', ' | '))
    ctx.close()

    # ---------- 7. TEMA CLARO + MOBILE ----------
    ctx, pg = novo(b, 390, 844)
    pg.goto(BASE + 'index.html'); pg.click('[data-alternar-tema]'); pg.wait_for_timeout(200)
    chk('tema claro aplicado e salvo', pg.evaluate("document.documentElement.dataset.tema + '/' + localStorage.getItem('vibe.tema')") == 'claro/claro')
    for nome in ['index', 'agendar', 'fidelidade', 'login', 'recuperar-senha']:
        pg.goto(BASE + nome + '.html'); pg.wait_for_timeout(250)
        w = pg.evaluate("document.documentElement.scrollWidth")
        chk(f'{nome} mobile sem rolagem horizontal', w <= 391, w)
    entrar(pg, 'admin', 'admin'); pg.wait_for_url('**/dashboard.html')
    for nome in ['dashboard', 'agenda', 'clientes', 'atendimento', 'caixa', 'relatorios', 'funcionarios', 'servicos', 'alterar-senha']:
        pg.goto(BASE + nome + '.html'); pg.wait_for_timeout(300)
        w = pg.evaluate("document.documentElement.scrollWidth")
        chk(f'{nome} mobile sem rolagem horizontal', w <= 391, w)
    pg.goto(BASE + 'dashboard.html'); pg.click('#btn-menu'); pg.wait_for_timeout(300)
    chk('menu off-canvas abre no mobile', pg.evaluate("document.body.classList.contains('menu-aberto') || document.getElementById('sidebar').classList.contains('aberta') || document.getElementById('btn-menu').getAttribute('aria-expanded')==='true'"))
    pg.screenshot(path='/tmp/s8/mobile_menu.png')
    ctx.close()
    b.close()
print(f'\nRESUMO: {len(ok)} OK, {len(falhas)} falhas; erros de console/página: {len(problemas)}')
for f in falhas: print('  FALHA:', f)
for x in problemas: print('  ', x)
